### ISSUE TITLE
GeneTonic does not load 

### ISSUE THREAD

**Issue by Rafaelsoler13** [federicomarini/GeneTonic#18]
Hi!

I was using GeneTonic, and now I get this message in R:

```
> library("GeneTonic")

Registered S3 method overwritten by 'htmlwidgets':
  method           from         
  print.htmlwidget tools:rstudio
Error: package or namespace load failed for ‘GeneTonic’:
 object ‘bs4TabPanel’ is not exported by 'namespace:bs4Dash'
```

And in the _bs4Dash_ I cannot see any package called _bs4TabPanel_

> ...
> bs4SidebarUserPanel	Create a Boostrap 4 dashboard main sidebar
> bs4SocialCard	AdminLTE3 social card
> bs4Sortable	BS4 sortable section
> bs4Stars	AdminLTE3 stars
> bs4TabCard	Create a Boostrap 4 tabCard
> bs4TabItem	Boostrap 4 dashboard body
> bs4TabItems	Boostrap 4 dashboard body
> bs4Timeline	AdminLTE3 timeline block
> bs4TimelineEnd	AdminLTE3 timeline block
> bs4TimelineItem	AdminLTE3 timeline block
> bs4TimelineItemMedia	AdminLTE3 timeline block
> ...

Could the package have been renamed?

**Comment by Rafaelsoler13** [comment]
They seem to have removed the function:

https://rinterface.github.io/bs4Dash/news/index.html#bs4dash-2-0-0-unreleased

**Comment by federicomarini** [comment]
Good catch, the release of `bs4Dash` is indeed fresh news.
Hopefully the developers are providing a drop-in replacement for that? I'll investigate 😉

**Comment by federicomarini** [comment]
BTW: for the time being, @Rafaelsoler13 - you can get it up and running 
```
devtools::install_version("bs4Dash", "0.5.0")
```

**Comment by Rafaelsoler13** [comment]
Thanks Federico! And great tool 👌😊

**Comment by federicomarini** [comment]
I put together a quick fix - available here: https://github.com/federicomarini/GeneTonic/tree/newbs4dash

You can install it via

```
devtools::install_github("federicomarini/GeneTonic@newbs4dash")
```

Could you give it a try on your machine please?

**Comment by Rafaelsoler13** [comment]
Yes! This is the output

`√  checking for file 'C:\Users\Usuario\AppData\Local\Temp\Rtmpa6TiCH\remotes44a03ab34e17\federicomarini-GeneTonic-6bb9772/DESCRIPTION' ... 
-  preparing 'GeneTonic': (361ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'GeneTonic_1.5.2.tar.gz'
   
Installing package into ‘C:/Users/Usuario/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package 'GeneTonic' ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'bs4Dash' 0.5.0 is being loaded, but >= 2.0.0 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Ejecución interrumpida
ERROR: lazy loading failed for package 'GeneTonic'
* removing 'C:/Users/Usuario/Documents/R/win-library/4.1/GeneTonic'
* restoring previous 'C:/Users/Usuario/Documents/R/win-library/4.1/GeneTonic'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/Usuario/AppData/Local/Temp/Rtmpa6TiCH/file44a04c816758/GeneTonic_1.5.2.tar.gz’ had non-zero exit status`

**Comment by Rafaelsoler13** [comment]
Yes! This is the output

```
√  checking for file 'C:\Users\Usuario\AppData\Local\Temp\Rtmpa6TiCH\remotes44a03ab34e17\federicomarini-GeneTonic-6bb9772/DESCRIPTION' ... 
-  preparing 'GeneTonic': (361ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'GeneTonic_1.5.2.tar.gz'
   
Installing package into ‘C:/Users/Usuario/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package 'GeneTonic' ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'bs4Dash' 0.5.0 is being loaded, but >= 2.0.0 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Ejecución interrumpida
ERROR: lazy loading failed for package 'GeneTonic'
* removing 'C:/Users/Usuario/Documents/R/win-library/4.1/GeneTonic'
* restoring previous 'C:/Users/Usuario/Documents/R/win-library/4.1/GeneTonic'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/Usuario/AppData/Local/Temp/Rtmpa6TiCH/file44a04c816758/GeneTonic_1.5.2.tar.gz’ had non-zero exit status
```

**Comment by federicomarini** [comment]
Oh, could you try that in a fresh R session? It seems the older bs4Dash was still loaded.

**Comment by Rafaelsoler13** [comment]
Yes! Now it works! :)

Could I suggest a couple of changes? It would be very interesting if it were also included with the KEGG or REACTOME pathways option, I think that the volcano plots and the heatmaps of the GO terms are too small (or maybe I don't know how to enlarge them), and finally I'm working with 5000 DEGs, for what the map of GO terms and its interactions is very crowded and does not turn out well.

Greetings and congratulations! :)

**Comment by federicomarini** [comment]
Thanks for the report!

> Could I suggest a couple of changes? It would be very interesting if it were also included with the KEGG or REACTOME pathways option

Well, you can use these sets anyway, it mostly depends on your upstream tool.

> , I think that the volcano plots and the heatmaps of the GO terms are too small (or maybe I don't know how to enlarge them), 

Probably best if you use the functions offline to have most control on the appearance. Say, in a RMarkdown report and then tweak fig.height and fig.width.

> and finally I'm working with 5000 DEGs, for what the map of GO terms and its interactions is very crowded and does not turn out well.

Oh, that is a huge bunch. Probably you can obtain similar or better polished results if you select DE with a higher degree of stringency. Say, a smaller FDR, or testing against a different null hypothesis (*not* subsetting for logFC post hoc, but rather using a TREAT-like approach if using edgeR, or the lfcThreshold parameter in DESeq2 - an example for that can be found in the vignettes, or is also what I did for the demo dataset)

Enjoy it, and thanks for the input!

**Comment by federicomarini** [comment]
FYI, https://github.com/federicomarini/GeneTonic/pull/19 is in now, so it should be available to all in the master branch, and soon in the version propagated in the Bioc build system

**Comment by lucius81** [comment]
> I put together a quick fix - available here: https://github.com/federicomarini/GeneTonic/tree/newbs4dash
> 
> You can install it via
> 
> ```
> devtools::install_github("federicomarini/GeneTonic@newbs4dash")
> ```
> 
> Could you give it a try on your machine please?

This worked for me !

**Comment by federicomarini** [comment]
Awesome, thanks @lucius81 for stepping in 😄 
I'll leave this one open for some time to give @Rafaelsoler13 time to check, and while not everyone might have updated both packages it could help as a reference (if one goes from scratch now, I am enforcing bs4Dash as >= 2.0.0 so it should not even bother)

**Comment by Rafaelsoler13** [comment]
Yes, it also worked for me :)
