### ISSUE TITLE
GeneTonic stopped working after packages update

### ISSUE THREAD

**Issue by acerverat** [federicomarini/GeneTonic#20]
GeneTonic shiny app was working fine, but when i tried to make a heatmap following the tutorial the whole R session crashed. I tried updating packages in R and now GeneTonic is broken and I can't reinstall. I get the following error: 
> library("GeneTonic")

Error: package or namespace load failed for ‘GeneTonic’:
 object ‘bs4TabPanel’ is not exported by 'namespace:bs4Dash'

Any help will be highly appreciated. Thanks

**Comment by federicomarini** [comment]
Hi @acerverat, this seems also related to #18 - a workaround is proposed, and a solution is in the works 😉 

It might be you did update recently `bs4Dash`, can you post the output of `sessionInfo()` to verify?

**Comment by federicomarini** [comment]
https://github.com/federicomarini/GeneTonic/pull/19 is now merged into master, so it is probably solved.
Can you please confirm @acerverat ?
Thanks!

**Comment by acerverat** [comment]
Hi,
I can confirm that the workaround solved the issue, but I haven't had time
to test if the updated version solves the issue entirely.
I will report back as soon as I can give it a try, I just didn't want to
leave this unanswered for the time being.
Thanks for your help, the tool is fantastic.

**Comment by federicomarini** [comment]
Awesome, thanks for both the update and the kind words!

**Comment by federicomarini** [comment]
Sticking to the latest version of all packages should actually result in a working version.
Can you please try with that?

**Comment by Malarkey73** [comment]
> Sticking to the latest version of all packages should actually result in a working version. Can you please try with that?

Thx 
I just installed it with Bioconductor. 
Do you mean use the current github version or the bioconductor dev version?

**Comment by federicomarini** [comment]
Bioc release version should be the most stable setup.
Bioc devel is often in sync with github.
I have R-4.1.2 on this machine and the release version works as expected

**Comment by Malarkey73** [comment]
> I have R-4.1.2 on this machine and the release version works as expected

okay thanks. I'm R4.0.4 and have been delaying an update while finishing a project. I can install another version and try again.

cheers

**Comment by federicomarini** [comment]
Ok, thanks for the update.
Let me know if you manage to solve it 😉
