### ISSUE TITLE
[Question]: Standing up GeneTonic on a shiny server

### ISSUE THREAD

**Issue by tamuanand** [federicomarini/GeneTonic#25]
Hi 

Thanks a lot for the great and cool work.

Is it easy enough to have GeneTonic as a shiny server _a la_ [ideal](https://github.com/federicomarini/ideal_serveredition) and [pcaExplorer](https://github.com/federicomarini/pcaExplorer_serveredition) 

When I do this below within RStudio, a browser does open up with the loaded dataset similar to what you have at http://shiny.imbei.uni-mainz.de:3838/GeneTonic/
```
library(GeneTonic)
GeneTonic()
example("GeneTonic", ask = FALSE)
```

Is there a way to replace the datasets etc via the browser - functionalities seen in ideal/pcaExplorer shiny server editions?

Thanks in advance

**Comment by federicomarini** [comment]
Hi @tamuanand , at the moment this is not possible, given that the format is a little more complex than the individual ones required by pcaExplorer and ideal.

We were considering to support the upload of a standardized format such as the GeneTonicList, for which you'd ideally need the RDS file (still not the textual input), that would be at least some step in that direction.

Not so straightforward as it would change the logic of a couple of things that go on in the app, but let's say it is worth a try once the bandwidth for this is available 😉

**Comment by federicomarini** [comment]
Closing this, as the functionality is now implemented in the recent release
