### ISSUE TITLE
GeneTonic with EdgeR

### ISSUE THREAD

**Issue by lucolotto** [federicomarini/GeneTonic#26]
Hi Federico,
First of all, thanks for the great package. It is a very useful and interesting tool. Really a great job! Thanks

I was wondering if you could adopt your library to accomodate also people that use edgeR for DE calling. I was thinking maybe at some sort of `shake` function that would take a DGEList object from edgeR and create a "fake" DEseqResult object, with just the minimal info needed for GeneTonic to work. Would that be possible?

Thanks a lot
Luca

**Comment by federicomarini** [comment]
Hi Luca,

Would the section in the Supplements of the recently published paper be something for your case?

https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04461-5

See Additional file 3 ->
 
<img width="748" alt="image" src="https://user-images.githubusercontent.com/7447478/147823777-b228369b-cdf9-4aab-b8c6-8c0bac6d39e8.png">

The function to convert between formats should already be a part of the DEformats package

**Comment by lucolotto** [comment]
That is exactly what I needed, thanks a lot Federico! Much appreciated. I also looked at your other projects, pretty impressive work. I will try also your `pcaExplorer` and `ideal` libraries

**Comment by federicomarini** [comment]
Perfect, glad it could help.
I could/should link to that content in the vignette of the package - will do that in the Bioc/GitHub devel branch for now 😉 

Can this one be safely closed otherwise?
Federico

p.s. Thanks for the kind words - if you are into single cell analysis, have a look at the iSEE package as well 🎉  (https://github.com/iSEE/iSEE)

**Comment by lucolotto** [comment]
Thanks! yes, for me you can safely close this.
I will have a look at iSEE as well for the sake of curiosity (I am not doing single cell sequencing at the moment, but in the future who knows!?!?). 

Happy 2022! 
Luca
