### ISSUE TITLE
Vignette cannot be built

### ISSUE THREAD

**Issue by dktanwar** [federicomarini/GeneTonic#3]
I was not able to build the vignette of the package. I also tried to execute each step manually, but it seems like some data is missing.

**Comment by federicomarini** [comment]
It could be needing the devel version of `macrophage`? That'd be my first guess.
You can circumvent/solve it with 

```
# if you run devel already
BiocManager::install("macrophage")
# otherwise
BiocManager::install("mikelove/macrophage")
```

Mike was kind enough to put the `gse` object in the data package, so there is no need of starting from the salmon quantifications.

**Comment by federicomarini** [comment]
Pinging @dktanwar on this - otherwise I can assume it can be safely closed?
F

**Comment by dktanwar** [comment]
Hi @federicomarini 

Sorry for the delay!

Yes, the installation is done properly with `build_vignettes`

**Comment by federicomarini** [comment]
Thanks for following up!
