### ISSUE TITLE
bg_ids datatype and creation 

### ISSUE THREAD

**Issue by DaniBlumstein** [federicomarini/GeneTonic#39]
Hi I'm working on using your package on my own data but I'm running into an issue with the bg_ids object. My dds object and res object look just like the one in the example but when I run my version of res_macrophage_IFNg_vs_naive$SYMBOL <- rowData(dds_macrophage)$SYMBOL I only get the symbols back

Thanks!
Dani

**Comment by federicomarini** [comment]
Assuming this one is solved on itself?

Anyway: if you would need the (ENSEMBL) identifiers, these are simply the rownames of the dds object
